name: nxengine-evo
base: core20
adopt-info: metadata

grade: stable
confinement: strict

apps:
  nxengine-evo:
    command: bin/launcher
    desktop: usr/share/applications/nxengine-evo.desktop
    common-id: org.nxengine.nxengine_evo
    plugs:
    - opengl
    - unity7
    - wayland
    - x11
    - desktop
    - audio-playback
    - joystick
parts:
  metadata:
    source: .
    plugin: nil
    override-pull: |
      snapcraftctl pull
      version="$(git describe --always | sed -e 's/-/+git/;y/-/./')"
      xsltproc --stringparam "VERSION" "$version" \
        --stringparam "DATE" "$(date +%Y-%m-%d)" \
        platform/xdg/appdata-add-version.xslt \
        platform/xdg/org.nxengine.nxengine_evo.appdata.xml \
        > platform/xdg/org.nxengine.nxengine_evo-snap.appdata.xml
    parse-info: [platform/xdg/org.nxengine.nxengine_evo-snap.appdata.xml]
    build-packages: [xsltproc]
  launcher:
    source: .
    plugin: dump
    organize:
      platform/snap/launcher.sh: bin/launcher
    prime:
      - bin/launcher
  cavestory:
    plugin: nil
    source: https://www.cavestory.org/downloads/cavestoryen.zip
  desktop-file:
    source: .
    plugin: dump
    organize:
      platform/snap/gui/nxengine-evo.desktop: usr/share/applications/nxengine-evo.desktop
      platform/xdg/org.nxengine.nxengine_evo.png: usr/share/icons/nxengine-evo.png
    prime:
      - usr/share/applications/nxengine-evo.desktop
      - usr/share/icons/nxengine-evo.png
  nxengine-evo:
    plugin: cmake
    source: .
    build-packages:
      - build-essential
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libpng-dev
    stage-packages:
      - libgl1-mesa-glx
      - libglew2.1
      - libglu1-mesa
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libpulse0
    override-build: |
        cp -r ../src/* .
        [ -d "build" ] && rm -r build
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        cd ../
        cp -r bin/ $SNAPCRAFT_PART_INSTALL/
        # Extract and install data
        cp ../../cavestory/src/CaveStory/Doukutsu.exe .
        ./bin/extract
        cp -r ../../cavestory/src/CaveStory/data/* data
        cp -r data/ $SNAPCRAFT_PART_INSTALL/bin
    after:
      - cavestory
      - glib-only
  translations:
    plugin: dump
    source: https://github.com/nxengine/translations/releases/download/v1.12/all.zip
    organize:
      data: bin/data
    prime:
      - bin/data
    after:
      - cavestory
      - nxengine-evo
  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
